name: Draft Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draft:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Development Release
        uses: robinraju/release-downloader@v1.9
        with:
          tag: nightly
          fileName: '*'
          tarBall: false
          zipBall: true
          out-file-path: 'dev'

      - name: Debug ZIP Contents
        run: unzip -l ${{ github.workspace }}/dev/geode-nightly.zip

      - name: Declare Version Variable
        id: ref
        shell: bash
        run: |
          VERSION=$(unzip -p ${{ github.workspace }}/dev/geode-nightly.zip geode-sdk-geode-*/VERSION | xargs)
          if [ -z "$VERSION" ]; then
            echo "VERSION is empty. Ensure the VERSION file exists in the ZIP."
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Test if release already exists
          set +e
          curl --fail "https://api.github.com/repos/MuhXd/geode-lite-repo/releases/tags/v$VERSION" --silent --output /dev/null
          RESULT=$?
          set -e

          if [ $RESULT -eq 0 ]; then
            echo "Release $VERSION already exists! Not replacing it."
            exit 1
          fi

      - name: Debug Files Before Move
        run: ls -la dev/

      - name: Move Files
        run: |
          mv dev/geode-*-android32.zip geode-v${{ steps.ref.outputs.version }}-android32.zip
          mv dev/geode-*-android64.zip geode-v${{ steps.ref.outputs.version }}-android64.zip
          mv dev/resources.zip resources.zip

      - name: Debug Files After Move
        run: ls -la .

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.ref.outputs.version }}
          name: Geode v${{ steps.ref.outputs.version }}
          body: |
            TODO before publishing:
             - mark if
